#! /bin/sh

###############
## autostart ##
###############

## hotkey daemon ##
sxhkd -c "$HOME"/.config/sxhkd/sxhkdrc &

## picom compositor ##
picom --config "$HOME"/.config/picom/picom.conf &

## set wallpaper ##
feh --bg-scale "$HOME"/.config/wallpapers/000000.jpg

## fixing the cursor ##
xsetroot -cursor_name left_ptr

## fast key movement ##
xset r rate 200 50

##################
## bspwm config ##
##################

bspc monitor -d 󰖟 󰳫        󰊗 

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52

bspc config single_monocle	 true
bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config paddingless_monocle	 true

bspc config focus_follows_pointer true
bspc config pointer_follows_focus false
bspc config pointer_motion_interval 15

bspc config normal_border_color "#2e3440"
bspc config active_border_color "#2e3440"
bspc config focused_border_color "#d8dee9"
bspc config presel_feedback_color "#2e3440"
