#! /bin/sh
#
#
export BSPWM_CONFIG="${XDG_CONFIG_HOME:-$HOME/.config}/bspwm"

INTERNAL_MONITOR="eDP-1"
EXTERNAL_MONITOR="HDMI-1"
if [[ "$1" = 0 ]]; then
	if xrandr -q | grep "${EXTERNAL_MONITOR} connected"; then
		bspc monitor "${EXTERNAL_MONITOR}" -d  1 2 3 4 5
		bspc monitor "${INTERNAL_MONITOR}" -d  6 7 8 9 10
		bspc wm -O "$EXTERNAL_MONITOR" "$INTERNAL_MONITOR"

	else
		bspc monitor "${INTERNAL_MONITOR}" -d 1 2 3 4 5 6 7 8 9 10
	fi
fi


######################################
## external script for window rules ##
######################################

bspc config external_rules_command "$HOME"/.config/bspwm/scripts/external_rules_command


##################
## bspwm config ##
##################

#bspc monitor -d 1 2 3 4
#bspc monitor -d 󰖟        󰊗  

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52

bspc config single_monocle	 true
bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config paddingless_monocle	 true

bspc config focus_follows_pointer true
bspc config pointer_follows_focus false
bspc config pointer_motion_interval 15

bspc config normal_border_color "#2e3440"
bspc config active_border_color "#2e3440"
bspc config focused_border_color "#d8dee9"
bspc config presel_feedback_color "#2e3440"


########################
## BSPWM window rules ##
########################

bspc rule -a 'Alacritty:Alacritty:htop task manager' state=floating rectangle=1414x611+572+413 center=on


###############
## autostart ##
###############

## Helper function to check for active process, if not found starts program on the background
_run() {
    if ! pgrep -x "${1}" &>/dev/null; then
        "$@" &
    fi
}

## hotkey daemon ##
sxhkd -c "$HOME"/.config/sxhkd/sxhkdrc &

## launch polybar
#"$HOME"/.config/polybar/scripts/launch_polybar.sh &

## picom compositor ##
picom --config "$HOME"/.config/picom/picom.conf &

## set wallpaper ##
#feh --bg-scale "$HOME"/.config/wallpapers/000000.jpg

## fixing the cursor ##
xsetroot -cursor_name left_ptr

## fast key movement ##
xset r rate 200 50

## Setup monitors, polybar and wallpaper ##
"$HOME"/.config/bspwm/scripts/bspwm_setup_monitors.sh &
