#!/bin/bash
while getopts ":i:e:" opt; do
  case $opt in
    i)INTERNAL_MONITOR="$OPTARG"
    ;;
    e)EXTERNAL_MONITOR="$OPTARG"
    ;;
    \?) echo "Invalid option -$OPTARG" >&2
    ;;
  esac
done
# Add default temp desktop because a minimum of one desktop is required per monitor
bspc monitor "$EXTERNAL_MONITOR" -a 7

# Move all desktops except the last default desktop to internal monitor
bspc desktop 1  --to-monitor "$INTERNAL_MONITOR"
bspc desktop 2 --to-monitor "$INTERNAL_MONITOR"
bspc desktop 3 --to-monitor "$INTERNAL_MONITOR"
bspc desktop 4 --to-monitor "$INTERNAL_MONITOR"
bspc desktop 5 --to-monitor "$INTERNAL_MONITOR"
 # delete default desktops
bspc desktop Desktop --remove
bspc desktop 7 --remove
bspc monitor "$EXTERNAL_MONITOR" --remove

 # reorder desktops
bspc monitor "$INTERNAL_MONITOR" -o 1 2 3 4 5 6
